### PR TITLE
Fixed riskfree function, added m2

### PR DESCRIPTION
**Pull request by Mr-Elysium**
Fixed riskfree() 
added m2
Now the correct riskfree function should be returned

### CODE REVIEW

**Comment by ishaantaylor** [comment]
@mcdallas what's the blocker to merge this?

**Comment by Mr-Elysium** [comment]
I do not know what you mean, I just saw that the m2 was nog yet implemented and I implemented it.

**Comment by mcdallas** [comment]
@ishaantaylor looks like there were changes to the treasury page recently https://home.treasury.gov/developer-notice-xml-changes we have to update the parser to pull the data from those XML feeds instead

**Comment by Mr-Elysium** [comment]
I was not aware of that, if need be, I am willing to rewrite the function to pull from xml data, actually yes, I will do that.

**Comment by mcdallas** [comment]
closing in favor of https://github.com/mcdallas/wallstreet/pull/41

**Pull request closed without merging**
